services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/chromadb_data:/data
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    restart: always

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: rag_backend
    ports:
      - "8001:8001"
    volumes:
      - ./src:/app
      - ./volumes:/app/volumes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - chromadb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rag_frontend
    ports:
      - "7860:7860"
    volumes:
      - ./src:/app
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8001