services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data
    restart: always

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: rag_backend
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - chromadb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rag_frontend
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8001